public class Constructor {

    
    //Lec.04 :Constructor and its types.


    //Constuctor : it is used to initialize an object(it is an instance or any entity).
    //it is defined as same name as class name and used to initialize an object.
    //it is of three types : 1).Default Constructor().--> automatically generated by compiler(set default values from getter or setter).
    //eg.on intellij constructor.java
    //2).Parametrized Constructor(parameter1 , parameter2) also known as customized constructor. --> it takes one and more than one parameters passed in it as arguments(10 ,20) --> to --> parameters(int x , int y).
    //eg.on intellij parametrize.java
    //3).copy constructor.it copied the property of another constructor in it.
    //copy constructor code --> :
    //copy constructor code --> :
    //public Constructor(Constructor c){
    //    this.x = c.x;
    //    this.y = c.y;
    //}
    //examlple on vs code.
    //Note : if we define any constructor then default constructor will not be created by compiler.
    public static void main(String[] args) {
        Constructor c1 = new Constructor(); //default constructor called here.
        Constructor c2 = new Constructor(10 , 20); //parametrized constructor called here.
        Constructor c3 = new Constructor(c2); //copy constructor called here.
        c1.display();
        c2.display();
        c3.display();
        System.out.println("Address of c2 = " + c2);
        System.out.println("Address of c3 = " + c3);

    }
    
    int x;
    int y;
    //default constructor
    public Constructor(){
        x = 0;
        y = 0;
    }
    //parametrized constructor
    public Constructor(int x , int y){
        this.x = x;
        this.y = y;
    }
    //copy constructor
    public Constructor(Constructor c){
        this.x = c.x;
        this.y = c.y;
    }
    public void display(){
        System.out.println("x = " + x + " , y = " + y);
        int m = x + y;
        System.out.println("your sum is : "+m);
    }

}
